name: Deploy to Preview Channel
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Expo CLI
        run: npm install -g expo-cli
      - name: Install dependencies
        run: npm install
      - name: Install expo-updates
        run: npm install expo-updates
      - name: Build and deploy app
        run: |
          expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
          expo publish --release-channel preview-${{ github.event.pull_request.number }}

      - name: Comment on pull request
        uses: actions/github-script@v4
        with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            const previewUrl = '${{ steps.preview_url.outputs.url }}';
            const releaseChannel = 'pr' + '${{ github.event.pull_request.number }}';
            const { data: { number } } = await github.rest.pulls.get(context.repo, context.payload.pull_request.number);
            await github.rest.issues.createComment({
            repo: context.repo.repo,
            owner: context.repo.owner,
            issue_number: number,
            body: `Preview URL: ${previewUrl}\nRelease Channel: ${releaseChannel}`
          });
