name: Publish Preview Expo app on Pull Request to Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Expo CLI
        run: npm install -g expo-cli
      - name: Install dependencies
        run: npm install
      - name: Install expo-updates
        run: npm install expo-updates
      - name: Build and deploy app
        run: |
          expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
          expo publish --release-channel preview-${{ github.event.number }}

      - name: Set output
        run: echo ::set-output name=url::https://expo.dev/@stein257/fiufitapp?release-channel=preview-${{ github.event.number }}
        id: output
      - name: Get deployment URL
        run: |
          echo "https://expo.dev/@stein257/fiufitapp?release-channel=preview-${{ github.event.number }}"
        id: url
      - name: Create comment with URL
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = '${{ steps.url.outputs.stdout }}';
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Your Expo app has been deployed to: ${url}`
            });

