name: Deploy Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Expo CLI
        run: npm install -g expo-cli
      - name: Install dependencies
        run: npm install
      - name: Install expo-updates
        run: npm install expo-updates
      - name: Build and deploy app
        run: |
          expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
          expo publish --release-channel pr${{ github.sha }}

      - name: Get preview URL
        id: preview_url
        run: echo "::set-output name=url::$(expo url:web --no-pwa --raw)"

      - name: Comment on pull request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const previewUrl = '${{ steps.preview_url.outputs.url }}';
            const releaseChannel = 'pr' + '${{ github.sha }}';
            const { data: { number } } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: number,
              body: `Preview URL: ${previewUrl}\nRelease Channel: ${releaseChannel}`
            });
