name: Deploy to Preview Channel
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Expo CLI
        run: npm install -g expo-cli
      - name: Install dependencies
        run: npm install
      - name: Install expo-updates
        run: npm install expo-updates
      - name: Build and deploy app
        run: |
          expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
          expo publish --release-channel preview-${{ github.event.number }}

      - name: Get Octokit
        id: octokit
        uses: octokit/request-action@v2.x
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Post comment
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequest } = await octokit.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const commentBody = `Preview deploy available at: ${deployUrl}`;

            await octokit.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequest.number,
              body: commentBody,
            });
        env:
          DEPLOY_URL: ${{ steps.deploy.outputs.preview_url }}
