name: Publish Preview Expo app on Pull Request to Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Expo CLI
        run: npm install -g expo-cli
      - name: Install dependencies
        run: npm install
      - name: Install expo-updates
        run: npm install expo-updates
      - name: Build and deploy app
        run: |
          expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
          expo publish --release-channel $(echo ${{ github.event.pull_request.number }}) --non-interactive --max-workers 1
        env:
          EXPO_CLI_NON_INTERACTIVE: 'true'
      - name: Get deployment URL
        run: |
          echo "https://$(expo url:web -c $(echo ${{ github.event.pull_request.number }}))"
